widget.title=Vite + React no Fluig
widget.instance=Instância
widget.counter=Contador: {0}
widget.configsTitle=Parâmetros Carregados (JSON):
widget.learnMore=Clique nos logos para saber mais.
widget.placeholderName=Digite um nome...
widget.placeholderEmail=Digite um e-mail...
widget.editPanelTitle=Configurações da Widget
widget.labelName=Nome para mostrar no Console:
widget.labelEmail=E-mail de Contato:
widget.btnSave=Salvar
widget.successSave=Configurações salvas com sucesso!
widget.errorSave=Não foi possível salvar as configurações.
